apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: java-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
          app: java-app
    spec:
      containers:
      - name: java-app
        image: localhost:5000/fill-heap:0.1
        ports:
        - containerPort: 80
