apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: java-app-aware
spec:
  replicas: 3
  template:
    metadata:
      labels:
          app: java-app-aware
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: "-XX:+UnlockExperimentalVMOptions  -XX:+UseCGroupMemoryLimitForHeap  -XshowSettings:vm"
      - name: java-app
        image: gcr.io/core-autobuilds-poc/fill-heap:0.1
        ports:
        - containerPort: 80
