apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: java-app-aware
spec:
  replicas: 3
  template:
    metadata:
      labels:
          app: java-app-aware
    spec:
      containers:
      - name: java-app-aware
        image: localhost:5000/fill-heap:0.1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "500Mi"
          limits:
            memory: "500Mi"
        env:
        - name: JAVA_OPTS
          value: "-XX:+UnlockExperimentalVMOptions  -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2 -XshowSettings:vm"